SGHR.Web/Controllers/CategoriasHabitacionController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System.Text.Json;
using SGHR.Web.Models;
using System.Text;
using SGHR.Web.Helpers.Abstraction;

namespace SGHR.Web.Controllers
{
    public class CategoriasHabitacionController : Controller
    {
        private readonly IHelper _helper;
        private List<CategoriaHabitacion>? categorias;
        

        public CategoriasHabitacionController(IHelper helper )
        { 
            _helper = helper;
        }

        public ActionResult Index()
        {
            
            return View();
        }

        public async Task<IActionResult> GetAllCategoriasHabitacion()
        {
            try
            {
                var response = await _helper.EjecutarHttpAsync("http://localhost:5217/api/",
                    cliente => cliente.GetAsync("CategoriasHabitacion/GetAllCategoriasHabitacion"));

                    if (response.IsSuccessStatusCode)
                    {
                        var responseString = await response.Content.ReadAsStringAsync();

                      

                        categorias = JsonSerializer.Deserialize<List<CategoriaHabitacion>>(responseString);

                    }
                
            }
            catch (Exception ex)
            {
                Console.WriteLine($"Error: {ex.Message}");
                Console.WriteLine($"StackTrece: {ex.StackTrace}");
                throw;
            }

            var model = categorias.Select(c => new CategoriasHabitacionModel
            {
                Id = c.Id,
                nombre = c.Nombre,
                descripcion = c.Descripcion,
                caracteristicas = c.Caracteristicas,
                tarifaBase = c.TarifaBase,
                estado = c.Estado
            }).ToList();

            return View("GetAllCategoriasHabitacion", model);
        }

        public async Task<IActionResult> CrearCategoriaHabitacion(CategoriaHabitacion categoria)
        {
            try
            {
                var json = JsonSerializer.Serialize(categoria);
                var content = new StringContent(json, Encoding.UTF8, "application/json");

                var response = await _helper.EjecutarHttpAsync("http://localhost:5217/api/", cliente => cliente.PostAsync("CategoriasHabitacion/CrearCategoriaHabitacion", content));

                if (response.IsSuccessStatusCode)
                    {
                        ModelState.AddModelError("", "Error al crear la categoria");
                    }
                
            }
            catch (Exception ex)
            {
                
                ModelState.AddModelError("", "Ocurrió un error al crear la categoría.");
            }

            return View("CrearCategoria");
        }


        [HttpGet]
        public async Task<IActionResult> EditarCategoria(int id)
        {
            
            var response = await _helper.EjecutarHttpAsync("http://localhost:5217/api/",
                      cliente => cliente.GetAsync("CategoriasHabitacion/GetAllCategoriasHabitacion"));

                 if (!response.IsSuccessStatusCode)
                 {
                      TempData["Error"] = "No se pudo cargar la categoría.";
                    return RedirectToAction("GetAllCategoriasHabitacion");
                 }

            var json = await response.Content.ReadAsStringAsync();
            var lista = JsonSerializer.Deserialize<List<CategoriaHabitacion>>(json);

            var categoria = lista.FirstOrDefault(c => c.Id == id);

                 if (categoria == null)
                     return NotFound();

            return View(categoria); 
        }

        [HttpPost]
        public async Task<IActionResult> EditarCategoria(CategoriaHabitacion categoria)
        {
            if (!ModelState.IsValid)
            {
                return View(categoria);
            }

            var contenido = new StringContent(JsonSerializer.Serialize(categoria), Encoding.UTF8, "application/json");

            var response = await _helper.EjecutarHttpAsync("http://localhost:5217/api/",
                    cliente => cliente.PutAsync($"CategoriasHabitacion/{categoria.Id}/ActualizarCategoria", contenido));
      

            if (response.IsSuccessStatusCode)
            {
                TempData["Success"] = "Categoría actualizada correctamente.";
                return RedirectToAction("GetAllCategoriasHabitacion");
            }

            TempData["Error"] = "Error al actualizar la categoría.";
            return View(categoria);
        }

          

        [HttpPost]
        public async Task<IActionResult> ConfirmadoEliminarCategoria(int id)
        {
            var response = await _helper.EjecutarHttpAsync("http://localhost:5217/api/",
                    cliente => cliente.DeleteAsync($"CategoriasHabitacion/{id}/EliminarCategoria"));

            if (response.IsSuccessStatusCode)
            {
                TempData["Success"] = "Categoría eliminada correctamente.";
                return RedirectToAction("GetAllCategoriasHabitacion");
            }

            TempData["Error"] = "No se pudo eliminar la categoría.";
            return RedirectToAction("GetAllCategoriasHabitacion", new { id }); 

            
        }
    }
}

SGHR.Web/Controllers/TarifasController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using SGHR.Web.Helpers.Abstraction;
using SGHR.Web.Models;
using System.Reflection;
using System.Text;
using System.Text.Json;

namespace SGHR.Web.Controllers
{
    public class TarifasController : Controller
    {
        private readonly HttpClient _httpClient;
        private readonly IHelper _helper;
        private TarifaModel _modelo;

        public TarifasController(HttpClient httpClient, IHelper helper) 
        { 
            _httpClient = httpClient;
            _helper = helper;
        }
        // GET: TarifasController
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public async Task<IActionResult> DefinirTarifaBase(int id)
        {

            var response = await _helper.EjecutarHttpAsync("http://localhost:5217/api/",
                     cliente => cliente.GetAsync("CategoriasHabitacion/GetAllCategoriasHabitacion"));

            if (!response.IsSuccessStatusCode)
                    return NotFound();
                
                    var responseString = await response.Content.ReadAsStringAsync();

                    var options = new JsonSerializerOptions
                    {
                        PropertyNameCaseInsensitive = true,
                    };


                var Listacategorias = JsonSerializer.Deserialize<List<CategoriasHabitacionModel>>(responseString, options);

                    var categoria = Listacategorias.FirstOrDefault(c => c.Id == id);

                    if (categoria == null)
                        return NotFound();

                var modelo = new TarifaModel
                {
                    CategoriaId = categoria.Id,
                    TarifaBase = categoria.tarifaBase
                };


                return View("DefinirTarifaBase", modelo);
            
        }

        [HttpPost]
        public async Task<IActionResult> DefinirTarifaBase(TarifaModel model)
        {
                if (!ModelState.IsValid)
                    return View(model);

                var jsonContent = JsonSerializer.Serialize(new
                {
                    precio = model.TarifaBase
                });

                var content = new StringContent(jsonContent, Encoding.UTF8, "application/json");

            var response = await _helper.EjecutarHttpAsync("http://localhost:5217/api/",
               cliente => cliente.PostAsync($"Tarifa/DefinirTarifaBase/{model.CategoriaId}", content));

                if (!response.IsSuccessStatusCode)
                {
                    ModelState.AddModelError("", "Error al actualizar la tarifa base.");
                    return View(model);
                }

                return RedirectToAction("GetAllCategoriasHabitacion", "CategoriasHabitacion");
            


        }

        
    }
}

SGHR.Web/Views/CategoriasHabitacion/CrearCategoria.cshtml
@model CategoriaHabitacion

<h2 class="mb-4">Crear Categoría de Habitación</h2>

<form asp-controller="CategoriasHabitacion" asp-action="CrearCategoriaHabitacion" method="post" class="needs-validation" novalidate>
    <div class="mb-3">
        <label asp-for="Nombre" class="form-label"></label>
        <input asp-for="Nombre" class="form-control" />
        <span asp-validation-for="Nombre" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Descripcion" class="form-label"></label>
        <input asp-for="Descripcion" class="form-control" />
        <span asp-validation-for="Descripcion" class="text-danger"></span>
    </div>

    <div class="mb-3">
        <label asp-for="Caracteristicas" class="form-label"></label>
        <input asp-for="Caracteristicas" class="form-control" />
        <span asp-validation-for="Caracteristicas" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Guardar</button>
</form>

SGHR.Web/Views/CategoriasHabitacion/EditarCategoria.cshtml
@model CategoriaHabitacion

<h2>Editar Categoría</h2>

<form asp-action="Editar" method="post">
    <input type="hidden" asp-for="Id" />

    <div class="form-group">
        <label asp-for="Nombre"></label>
        <input asp-for="Nombre" class="form-control" />
    </div>

    <div class="form-group">
        <label asp-for="Descripcion"></label>
        <textarea asp-for="Descripcion" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label asp-for="Caracteristicas"></label>
        <textarea asp-for="Caracteristicas" class="form-control"></textarea>
    </div>

    <div class="form-group">
        <label asp-for="TarifaBase"></label>
        <input asp-for="TarifaBase" class="form-control" type="number" step="0.01" />
    </div>

    <div class="form-group">
        <label asp-for="Estado"></label>
        <select asp-for="Estado" class="form-control">
            <option value="true">Activa</option>
            <option value="false">Inactiva</option>
        </select>
    </div>

    <button method="post" asp-controller="CategoriasHabitacion" asp-action="EditarCategoria"type="submit" class="btn btn-primary">Guardar cambios</button>
    <a asp-action="GetAllCategoriasHabitacion" class="btn btn-secondary">Cancelar</a>
</form>

SGHR.Web/Views/CategoriasHabitacion/EliminarCategoria.cshtml
@model CategoriaHabitacion

<h3>¿Quieres eliminar la categoría "@Model.Nombre"?</h3>

<form asp-action="EliminarConfirmado" method="post">
    <input type="hidden" asp-for="Id" />
    <button type="submit" class="btn btn-danger">Eliminar</button>
    <a asp-action="GetAllCategoriasHabitacion" class="btn btn-secondary">Cancelar</a>
</form>

SGHR.Web/Views/CategoriasHabitacion/GetAllCategoriasHabitacion.cshtml
@model List<CategoriasHabitacionModel>

@if (Model == null || !Model.Any())
{
    <p>No hay categorías para mostrar.</p>
}
<table class="table">
    <thead>
        <tr>
            <th>ID</th>
            <th>Nombre</th>
            <th>Descripción</th>
            <th>Caractersitcas</th>
            <th>Tarifa Base</th>
            <th>Estado</th>
            <th>Acciones</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var categoria in Model)
        {
            <tr>
                <td>@categoria.Id</td>
                <td>@categoria.nombre</td>
                <td>@categoria.descripcion</td>
                <td>@categoria.caracteristicas</td>
                <td>@categoria.tarifaBase</td>
                <td>@categoria.EstadoTexto</td>
                <td></td>
                <td>
                    <a method="get" asp-controller="CategoriasHabitacion" asp-action="EditarCategoria" asp-route-id="@categoria.Id" class="btn btn-warning">Editar</a>

                    <form asp-controller="CategoriasHabitacion" asp-action="ConfirmadoEliminarCategoria" asp-route-id="@categoria.Id" method="post" style="display:inline;">
                        <button type="submit" class="btn btn-danger" onclick="return confirm('¿Estás seguro de que deseas eliminar esta categoría?')">Eliminar</button>
                    </form>

                    <a method="get" asp-controller="Tarifas" asp-action="DefinirTarifaBase" asp-route-id="@categoria.Id" class="btn btn-primary">Definir Tarifa Base</a>
                </td>
            </tr>
        }
    </tbody>
</table>